image: golang:alpine

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apk add build-base
  script:
    - make build

coverage:
  stage: test
  before_script:
    - apk add build-base
  script:
    - make test